github:
  defaultBranch: main
  defaultReviewers:
    - '@serpro69'
    - '@0xbad-bot'
  autoAssignReviewer: true
diff:
  createAsDraft: false
  autoUpdatePR: true
  includeCommitMessages: true
  enableStacking: true
  defaultBase: ""
  showStackingWarnings: true
  templatePath: ""
  requireTestPlan: true
  linearEnabled: false
  linearDefaultProject: ""
land:
  defaultMergeMethod: squash
  deleteLocalBranch: true
  deleteRemoteBranch: true
  requireApproval: true
  requireCI: true
output:
  verbose: false
  quiet: false
  json: false
  color: true
